### ISSUE TITLE
update docs on how to make a challenge leaderboard

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#308]
http://docs.synapse.org/articles/challenge_administration.html#create-a-leaderboard

@thomasyu888 notes these are really out of date.

**Comment by brucehoff** [comment]
The document should explain:
- leaderboards allow you to display submission annotations in a tabular form.  By annotation submissions with scores you can display a leaderboard showing who is doing the best in the challenge;
- first go to the Admin table of the challenge project and get the ID of the Evaluation of interest;
- to edit a wiki and choose `Insert` > `Leaderboard`
- enter a query of the form "Select * from Evaluation_12345" where 12345 is the ID from the first step
- if you have some annotations already then you can click "refresh columns" to add display columns for the existing annotations.  Otherwise you have to add the columns manually.
- you can reorder the columns and choose what to sort by
- keep in mind that "private" annotations will not be visible to participants (only to challenge admin's)

**Comment by meredithslota** [comment]
I've taken @brucehoff's suggestions and added them to the doc, and clarified where possible. I suspect that we'll migrate Leaderboards to their own article later on, but this should do for now.
