### ISSUE TITLE
update 'file and versioning' to include upload link as entity

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/synapseDocs#321]
Can it be part of 'Uploading a File' as "Upload link as an entity"?

**Comment by meredithslota** [comment]
Relates to adding a files as a URL (and having that URL create an entity).

**Comment by meredithslota** [comment]
We can also document how to use Synapse in a "local" mode - e.g. files on your computer. Lets you work with local files on your computer that others cannot access and then convert/upload the "real" file when you are ready to make it public. Allows you to make the existence of the file public in advance of releasing the file itself because the file remains local. 

Something something about "associating" files from @kdaily that I don't understand really.

**Comment by ychae** [comment]
Add examples/explanations of how to link files stored on non-Synapse storage (eg Amazon S3, SFTP, FTP, http, etc). 

Currently (for http and ftp) the sync function takes a URL and the web client allows you to link to these files, but instructions are missing. Some instructions exist for SFTP and Amazon S3 in the Custom Storage Locations article.

**Comment by kelshmo** [comment]
We document storing files in S3 [here](https://docs.synapse.org/articles/custom_storage_location.html). It sounds like the initial issue was a request to document uploading urls as file entities. While this approach is useful for surfacing data with file views, it is rather specific and I think is better suited for a vignette or "In-practice" article. Closing for now, but anyone can re-open if the interest to document this functionality returns.
