### ISSUE TITLE
Document bulk upload in synapser

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#348]
http://docs.synapse.org/articles/uploading_in_bulk.html is missing instructions for R client, and @vortexing needs it.

**Comment by kimyen** [comment]
oh, I didn't realized that this one is assigned to me. Yes, please bump this to the September milestone. `synapserutils` is available on `ran`. Hence, I am unblocked. However, I don't think I will get to finish this `SynapseDocs` Github ticket this week.

**Comment by meredithslota** [comment]
Shifting to December milestone.

**Comment by kimyen** [comment]
Most of the instructions are available here: https://github.com/Sage-Bionetworks/synapserutils. TODOs: copy this to the docs article and open a PR.

**Comment by kimyen** [comment]
@meredithslota , per our discussion last week, to reduce code examples out-of-date, I think we can just link to synapserutils doc from http://docs.synapse.org/articles/uploading_in_bulk.html.

What do you think about linking to the README of synapserutils package? Or should I setup the doc site for the synapserutils repository as well?

**Comment by meredithslota** [comment]
@kimyen I'd like to start with removing existing code examples and pointing to CORE Python client package -- unsure about the utils package. What kind of documentation exists for it?

**Comment by kimyen** [comment]
The utils package in the Python client includes functions that allows users to do things in bulk/ recursively. 
Documentation includes:
* https://docs.synapse.org/articles/uploading_in_bulk.html
* https://python-docs.synapse.org/build/html/synapseutils.html#module-synapseutils (this is a reference doc, rather than a vignette style)
* https://github.com/Sage-Bionetworks/synapserutils

**Comment by kimyen** [comment]
This is done.
