### ISSUE TITLE
Check python client code examples against 1.9.0

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#394]
Need to verify that code examples work.

**Comment by kimyen** [comment]
Generally, yes. 
I think some of the docs example is out of date. If we do a massive check on all code example once, in each release, the amount of check will be minimum and related to the feature/ bug fix that we mention in the release notes. 
I can definitely update the code example while releasing a new version. Anything else, like general practices, how to do something, ... if we change the approach, I may need help rewriting the docs/ articles instead of just updating the code example.

**Comment by kimyen** [comment]
@meredithslota I kept on forgetting about this issue because the Python client release workflow is in Jira, and not link to this. I think the IT ticket @ychae created for supporting docs will help with the long term planning of keeping the docs content up-to-date. If this ticket needs to be done asap, please ping me.

**Comment by meredithslota** [comment]
Nah. In fact, I think we should probably close this as a "Won't Do" and move ahead with the other plan. :)
