### ISSUE TITLE
Synapser table page has wrong reference to synGetTableColumns argument

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseDocs#573]
On the `synapser` table doc page, the `synGetTableColumns` column uses a `tableid` as an argument when in reality it requires a table schema.

**Comment by kelshmo** [comment]
@sgosline Can you provide a link to this error?

**Comment by sgosline** [comment]
https://r-docs.synapse.org/articles/tables.html#changing-table-structure

**Comment by kimyen** [comment]
@sgosline ,

Actually, I look at the code and the function should work with the table ID as input. The docs could be improved. Can you verify that you cannot use this function with table ID only? If so, I would keep this ticket. Otherwise, I would open a ticket in the Python client to fix the error. (The R docs about specific argument inherit from the Python client docs.)

**Comment by sgosline** [comment]
It definitely didn't work, i will try to create steps to repro the issue later this week.

**Comment by kimyen** [comment]
I created https://sagebionetworks.jira.com/browse/SYNR-1421 to track this issue since the docs is generated from the synapser client code base.
