### ISSUE TITLE
Update Projects page

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#594]
Replace project content in https://docs.synapse.org/articles/making_a_project.html with: 

Projects are "containers" and group relevant content and people together. You can:
- Link and share content with others 
- Organize data, metadata, analysis, and documentation
- Use only the features you need
- Create multiple projects if needed

**Comment by Aryllen** [comment]
After discussion today, update by:

- Removing **Full Programmatic API...** and **Describe and Version** bullets
- Add any bullets from above that are not covered and fit
- Make "Create Your First Project" be "Create a Project" and remove it as a subheading (make on same header level as above section)
- Get the instructions for how to create a project from Getting Started guide since it looks nicer
- Remove the part about visiting the Getting Started guide
