### ISSUE TITLE
Category for tabular data in wiki

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#680]
- Where should [this article](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/using_tabular_data_in_wikis.md) live?

**Comment by kelshmo** [comment]
Add to Data Management

**Comment by Dumindaaa** [comment]
Very Sorry Kelsey, I know this is closed but looking at this properly, I see that it could also live in "Collaboration and Communication" since it requires knowledge from both Data Management and Collab & Comm", and seems like a feature that is more about collaborating with data, not managing it.

I guess the main question is, what is the main use case(s) for this ? At what point would I want to use this feature? When I am setting up a project and managing data? Or when I have done that, and am trying to make the data available to collaborators?
